"""Public API for BlobNet training, evaluation, and synthetic data generation."""

from blobnet.loss_func import CombinedGaussianLoss
from blobnet.metrics import (
    aggregate_localization_metrics,
    evaluate_heatmap_localization,
    evaluate_model_localization,
    extract_subpixel_peak_positions,
    plot_localization_result,
)
from blobnet.networks import UNet, Unet, available_model_variants, build_model, build_unet
from blobnet.synthetic import (
    AseStructureProjectionConfig,
    ImageFormationConfig,
    PeriodicLatticeConfig,
    PointCloud,
    RandomMicroscopeImageConfig,
    SavedMicroscopeDataset,
    SyntheticMicroscopeDataset,
    TightSpacingRandomMicroscopeImageConfig,
    build_ase_structure_unit_cell,
    build_generalization_dataloaders,
    build_synthetic_dataloaders,
    generate_microscope_image,
    plot_microscope_image,
    point_cloud_from_config,
    render_microscope_image,
    sample_lattice_points,
    sample_random_points,
    sample_structure_points,
    sample_tight_spacing_random_points,
    save_microscope_dataset,
    save_microscope_dataset_splits,
    save_microscope_preview,
)
from blobnet.utils import resolve_torch_device, train_model

__all__ = [
    "AseStructureProjectionConfig",
    "CombinedGaussianLoss",
    "ImageFormationConfig",
    "PeriodicLatticeConfig",
    "PointCloud",
    "RandomMicroscopeImageConfig",
    "SavedMicroscopeDataset",
    "SyntheticMicroscopeDataset",
    "TightSpacingRandomMicroscopeImageConfig",
    "UNet",
    "Unet",
    "aggregate_localization_metrics",
    "available_model_variants",
    "build_ase_structure_unit_cell",
    "build_generalization_dataloaders",
    "build_model",
    "build_synthetic_dataloaders",
    "build_unet",
    "evaluate_heatmap_localization",
    "evaluate_model_localization",
    "extract_subpixel_peak_positions",
    "generate_microscope_image",
    "plot_microscope_image",
    "plot_localization_result",
    "point_cloud_from_config",
    "render_microscope_image",
    "resolve_torch_device",
    "sample_lattice_points",
    "sample_random_points",
    "sample_structure_points",
    "sample_tight_spacing_random_points",
    "save_microscope_dataset",
    "save_microscope_dataset_splits",
    "save_microscope_preview",
    "train_model",
]
